### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by lostie** [DocSpring/docspring-ruby#1]
While using ruby 2.7 I'm currently getting a lot of these warnings:

```shell
.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/docspring-1.0.0/lib/docspring/api_client.rb:284: warning: URI.escape is obsolete
```

More info: https://ruby-doc.org/stdlib-2.6.3/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description

**Comment by ndbroadbent** [comment]
Hello, thanks for letting me know about this! I will try to update OpenAPI generator and our client library to remove this warning for Ruby 2.7.

**Comment by berkos** [comment]
👋  I was wondering if there are any updates for this.  `URI.escape` is not available anymore in Ruby `3.0.0`. Thanks!

**Comment by ndbroadbent** [comment]
Hi @berkos, sorry about the delay on this issue! That's a good point, and we need to change these to `CGI.escape`. I will try to prioritize this and get this fixed soon!

**Comment by berkos** [comment]
Hi @ndbroadbent. Thanks for looking on this, I have a possible work around [here](https://github.com/berkos/docspring-ruby/commit/875496aa68a10c8b2c61920cc97e2cedfdd8e023) but introduces an extra dependancy gem. Similar approach with wasabi gem [here](https://github.com/savonrb/wasabi/pull/81). Unfortunately I was not able to run the tests locally for docspring-ruby even on master branch since I might be missing some configuration.  Let me know if you'd like me to open a PR with this commit. Thanks!

**Comment by ndbroadbent** [comment]
Thanks for looking into this! This gem is a bit of a tricky situation, since the code is actually auto-generated from the [openapi-generator tool](https://github.com/OpenAPITools/openapi-generator). And the test suite is actually some end-to-end integration tests that rely on some private code (it starts the real DocSpring application server), so it can't be run independently. 

But I am happy to test the addressable workaround and push a new version. I'll let you know once that is live!

**Comment by berkos** [comment]
Hi @ndbroadbent. I was wondering if you have any updates on this. Thanks

**Comment by ndbroadbent** [comment]
Hi everyone, sorry for the delay! I've just pushed version `1.4.0` of the `docspring` gem to Rubygems, which will fix this `URI.escape` deprecation warning. Thanks!
